### PR TITLE
Resolve fields to display their correct values

### LINKED ISSUE #8: Bug: Does not show resolved display values
I ran into this issue when using a Select within the Polymorphic fields. On the display screen this would show the key value, even when using the displayUsingLabels method.

Invalid display valud

### PR DESCRIPTION
**Pull request by m2de**
This will ensure that fields show the correctly resolved display value to resolve #8 

E.g. `Select::make('Gender')->options(['male', 'female'])->displayUsingLabels();` will now correctly show `Male` and `Female` instead of `0` and `1` on display/index views.

Correct display value shown

### CODE REVIEW

**Comment by michielkempen** [comment]
Thanks for the PR @m2de!

**Comment by horaceho** [comment]
As of Nova v1.1.4., this PR breaks display of ````Text::make()````, which shows '—' only, as described in: https://github.com/michielkempen/nova-polymorphic-field/issues/12

**Comment by kingreym** [comment]
Agree with @horaceho , will someone fix that?

**Comment by carlosjac** [comment]
Agree with @horaceho , will someone fix that?

**Pull request merged**
